name: PotatoSK
description: PotatoSK fr
authors: [MCdragonmasters]
website: https://github.com/MCdragonmasters/PotatoSK
version: @version@
main: com.mcdragonmasters.PotatoSK.PotatoSK
api-version: '1.20'
depend:
  - Skript
